//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamingKeypressOverlay.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GamingKeypressOverlay.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT.
        /// </summary>
        public static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and AI&apos;s code :D.
        /// </summary>
        public static string AboutMadeWithCode {
            get {
                return ResourceManager.GetString("AboutMadeWithCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Made with Marc&apos;s brain.
        /// </summary>
        public static string AboutMadeWithBrain {
            get {
                return ResourceManager.GetString("AboutMadeWithBrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard &amp; Mouse Overlay.
        /// </summary>
        public static string AboutAppName {
            get {
                return ResourceManager.GetString("AboutAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        public static string KeyboardModeFull {
            get {
                return ResourceManager.GetString("KeyboardModeFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming (Shooter).
        /// </summary>
        public static string KeyboardModeGaming {
            get {
                return ResourceManager.GetString("KeyboardModeGaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string MenuLanguage {
            get {
                return ResourceManager.GetString("MenuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string MenuLanguageEnglish {
            get {
                return ResourceManager.GetString("MenuLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string MenuLanguageFrench {
            get {
                return ResourceManager.GetString("MenuLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Mode.
        /// </summary>
        public static string MenuKeyboardMode {
            get {
                return ResourceManager.GetString("MenuKeyboardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string MenuOptions {
            get {
                return ResourceManager.GetString("MenuOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Mode.
        /// </summary>
        public static string MenuPerformanceMode {
            get {
                return ResourceManager.GetString("MenuPerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string MenuColors {
            get {
                return ResourceManager.GetString("MenuColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application crashed. Crash report saved to: {0}.
        /// </summary>
        public static string MessageCrashReported {
            get {
                return ResourceManager.GetString("MessageCrashReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed. Please restart the application for full effect..
        /// </summary>
        public static string MessageLanguageChanged {
            get {
                return ResourceManager.GetString("MessageLanguageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Input initialization failed. Using fallback mode..
        /// </summary>
        public static string MessageRawInputFailed {
            get {
                return ResourceManager.GetString("MessageRawInputFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is already running!.
        /// </summary>
        public static string MessageApplicationRunning {
            get {
                return ResourceManager.GetString("MessageApplicationRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop / Normal Usage.
        /// </summary>
        public static string PerformanceModeDesktop {
            get {
                return ResourceManager.GetString("PerformanceModeDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Competitive Gaming.
        /// </summary>
        public static string PerformanceModeCompetitive {
            get {
                return ResourceManager.GetString("PerformanceModeCompetitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaming Keypress Overlay.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⌨️ Keyboard and Mouse Overlay.
        /// </summary>
        public static string TitleBarText {
            get {
                return ResourceManager.GetString("TitleBarText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options (ESC).
        /// </summary>
        public static string ToolTipOptions {
            get {
                return ResourceManager.GetString("ToolTipOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        public static string ToolTipMinimize {
            get {
                return ResourceManager.GetString("ToolTipMinimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximize / Restore.
        /// </summary>
        public static string ToolTipMaximize {
            get {
                return ResourceManager.GetString("ToolTipMaximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ToolTipClose {
            get {
                return ResourceManager.GetString("ToolTipClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string LabelStyle {
            get {
                return ResourceManager.GetString("LabelStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard Mode:.
        /// </summary>
        public static string LabelKeyboardMode {
            get {
                return ResourceManager.GetString("LabelKeyboardMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse Position:.
        /// </summary>
        public static string LabelMousePosition {
            get {
                return ResourceManager.GetString("LabelMousePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Mode.
        /// </summary>
        public static string LabelPerformanceMode {
            get {
                return ResourceManager.GetString("LabelPerformanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Mouse Position.
        /// </summary>
        public static string CheckBoxShowMousePosition {
            get {
                return ResourceManager.GetString("CheckBoxShowMousePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right (Right-handed).
        /// </summary>
        public static string MousePositionRight {
            get {
                return ResourceManager.GetString("MousePositionRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left (Left-handed).
        /// </summary>
        public static string MousePositionLeft {
            get {
                return ResourceManager.GetString("MousePositionLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMING KEYBOARD.
        /// </summary>
        public static string LabelGamingKeyboard {
            get {
                return ResourceManager.GetString("LabelGamingKeyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAST INPUT: .
        /// </summary>
        public static string LabelLastInput {
            get {
                return ResourceManager.GetString("LabelLastInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAMING MOUSE.
        /// </summary>
        public static string LabelGamingMouse {
            get {
                return ResourceManager.GetString("LabelGamingMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POSITION.
        /// </summary>
        public static string LabelPosition {
            get {
                return ResourceManager.GetString("LabelPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X: .
        /// </summary>
        public static string LabelX {
            get {
                return ResourceManager.GetString("LabelX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y: .
        /// </summary>
        public static string LabelY {
            get {
                return ResourceManager.GetString("LabelY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTIVE INPUTS.
        /// </summary>
        public static string LabelActiveInputs {
            get {
                return ResourceManager.GetString("LabelActiveInputs", resourceCulture);
            }
        }
    }
}
